version: '2'

services:
  arango:
    image: arangodb:latest
    hostname: arango
    ports:
      - "8529:8529"
    volumes:
      - /tmp/arango:/var/lib/arangodb
    environment:
      - ARANGO_NO_AUTH=1
      - ARANGO_ROOT_PASSWORD=password
